/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestarsala;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego Calvo R
 */
public class MostrarReservas extends javax.swing.JFrame {

    /**
     * Creates new form Reservas
     */
    DefaultListModel modeloLista = new DefaultListModel();
    Nodo PTR;
    Nodo RTP;
    Nodo p;
    boolean sw = false;
    int entera;
    String code;
    Usuario obj;

    public MostrarReservas() {

        initComponents();
        this.setLocationRelativeTo(null);
        RList.setModel(modeloLista);
        List.setVisible(false);
        codefield.setVisible(false);
        go.setVisible(false);
        codlabel.setVisible(false);
        RList.setVisible(false);
        BACK.setVisible(false);

        PTR = View.PTR;

        RTP = View.RTP;
    }

    public void mostrarRoom() {

        p = p.link2;
        while (p != null) {
            if (!p.codigo.equals("")) {
                obj = new Usuario(p.name, p.codigo, p.horario);
                modeloLista.addElement(obj);
            }

            p = p.link2;
        }

    }

    public void mostrarUser() {
        code = codefield.getText();
        try {
            sw = false;
            entera = Integer.parseInt(code);
            p = RTP;
            while (p != null && sw == false) {
                if (p.codigo.equals(code)) {
                    sw = true;
                    p = p.link4;
                    while (p != null) {
                        obj = new Usuario(p.name, p.codigo, p.horario);
                        modeloLista.addElement(obj);
                        p = p.link4;

                    }
                } else {
                    p = p.link3;
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        List = new javax.swing.JList<>();
        userbutton = new javax.swing.JButton();
        roombutton = new javax.swing.JButton();
        codefield = new javax.swing.JTextField();
        codlabel = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        RList = new javax.swing.JList<>();
        backtofuture = new javax.swing.JButton();
        go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel1.setText("RESERVAS:");

        List.setBackground(new java.awt.Color(204, 204, 204));
        List.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "SALON DE PROYECCIONES", "AUDITORIO", "AULA DEL K" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(List);

        userbutton.setText("USUARIOS");
        userbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userbuttonActionPerformed(evt);
            }
        });

        roombutton.setText("SALAS");
        roombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roombuttonActionPerformed(evt);
            }
        });

        codlabel.setText("CODIGO:");

        BACK.setText("BACK");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });

        RList.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(RList);

        backtofuture.setText("VOLVER AL MENU PRINCIPAL");
        backtofuture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtofutureActionPerformed(evt);
            }
        });

        go.setText("GO");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(userbutton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roombutton))
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BACK)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backtofuture))
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codefield, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(go)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userbutton)
                    .addComponent(roombutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codlabel)
                    .addComponent(codefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(go))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BACK)
                    .addComponent(backtofuture))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMouseClicked

        RList.setVisible(true);
        modeloLista.clear();
        if (null != this.List.getSelectedValue()) {
            switch (this.List.getSelectedValue()) {
                case "AUDITORIO":
                    p = PTR.link1;
                    mostrarRoom();

                    break;
                case "AULA DEL K":
                    p = PTR.link1.link1;
                    mostrarRoom();

                    break;
                case "SALON DE PROYECCIONES":
                    p = PTR;
                    mostrarRoom();

                    break;
                default:
                    break;
            }
        }

    }//GEN-LAST:event_ListMouseClicked

    private void userbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userbuttonActionPerformed
        codefield.setVisible(true);
        codlabel.setVisible(true);
        BACK.setVisible(true);
        go.setVisible(true);
        userbutton.setVisible(false);
        roombutton.setVisible(false);
    }//GEN-LAST:event_userbuttonActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        List.setVisible(false);
        codefield.setVisible(false);
        codlabel.setVisible(false);
        RList.setVisible(false);
        go.setVisible(false);
        BACK.setVisible(false);
        userbutton.setVisible(true);
        roombutton.setVisible(true);
        RList.setVisible(false);

    }//GEN-LAST:event_BACKActionPerformed

    private void roombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roombuttonActionPerformed
        BACK.setVisible(true);
        List.setVisible(true);

        userbutton.setVisible(false);
        roombutton.setVisible(false);
    }//GEN-LAST:event_roombuttonActionPerformed

    private void backtofutureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtofutureActionPerformed
        Login.v.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_backtofutureActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed

        RList.setVisible(true);
        modeloLista.clear();
        mostrarUser();
    }//GEN-LAST:event_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JList<String> List;
    private javax.swing.JList<String> RList;
    private javax.swing.JButton backtofuture;
    private javax.swing.JTextField codefield;
    private javax.swing.JLabel codlabel;
    private javax.swing.JButton go;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton roombutton;
    private javax.swing.JButton userbutton;
    // End of variables declaration//GEN-END:variables
}
